{{- if and .Values.embeddings.enabled .Values.embeddings.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openwebui-kth-cluster-helm.embeddingsServiceAccountName" . }}
  namespace: {{ include "openwebui-kth-cluster-helm.namespace" . }}
  labels:
    {{- include "openwebui-kth-cluster-helm.embeddingsLabels" . | nindent 4 }}
{{- end }}
