{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "openwebui-kth-cluster-helm.fullname" . }}
  namespace: {{ include "openwebui-kth-cluster-helm.namespace" . }}
spec:
  hostnames:
    {{- range .Values.gateway.hostnames }}
    - {{ . | quote }}
    {{- end }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: default
      namespace: gateway
      port: 443
  rules:
    {{- if and .Values.docs.enabled .Values.docs.gateway.paths }}
    {{- range .Values.docs.gateway.paths }}
    - matches:
      - path:
          type: {{ default "PathPrefix" .type }}
          value: {{ .path | quote }}
      backendRefs:
      - name: {{ include "openwebui-kth-cluster-helm.docsName" $ | quote }}
        port: {{ $.Values.docs.service.port }}
    {{- end }}
    {{- end }}
    - backendRefs:
      - name: {{ include "openwebui-kth-cluster-helm.fullname" . | quote }}
        port: {{ .Values.service.port }}
{{- end }}
