{{- if and .Values.tailscale.enabled .Values.tailscale.authSecret.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tailscale.authSecret.name }}
  namespace: {{ include "openwebui-kth-cluster-helm.namespace" . }}
  labels:
    {{- include "openwebui-kth-cluster-helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.tailscale.authSecret.key }}: {{ .Values.tailscale.authSecret.value | quote }}
{{- end }}
