apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openllm

resources:
- backup-cronjob.yaml
- restore-CronJob.yaml
- PersistentVolumeClaim.yaml
- NetworkPolicy.yaml
- application.yaml
- schedule.yaml

configMapGenerator:
- files:
  - backup-postgresql.sh
  name: backup-scripts
  options:
    disableNameSuffixHash: true
