---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-backup
  labels:
    storage: postgresql-backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi