#!/usr/bin/env bash
# bootstrap.sh <login|compute> [--check]
#
# Installs this repository's files to their host paths, per the table in README.md.
# Idempotent: safe to run after every `git pull`. Never touches secrets.
#
#   ./bootstrap.sh compute       # a compute node: vllm@ and vllm-multinode@ units, model confs
#   ./bootstrap.sh login         # the login node: litellm units and routing table
#   ./bootstrap.sh compute --check   # report differences, change nothing
#
# Re-run after pulling if any unit file or model conf changed. Configuration under
# multi-node/ is read straight from the checkout and needs no install step.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROLE="${1:-}"
CHECK=0
[ "${2:-}" = "--check" ] && CHECK=1
[ "${1:-}" = "--check" ] && { CHECK=1; ROLE="${2:-}"; }

case "$ROLE" in
  login|compute) ;;
  *) echo "usage: $(basename "$0") <login|compute> [--check]" >&2; exit 64 ;;
esac

UNITS="$HOME/.config/systemd/user"
changed=0
missing=0

# Fail early rather than skipping everything and reporting success.
for d in proxy single-node multi-node; do
  [ -d "$REPO/$d" ] || {
    echo "FATAL: expected directory $REPO/$d does not exist." >&2
    echo "       Run this from inside vllm-03-c3se-podman, in a checkout that has" >&2
    echo "       the proxy/, single-node/ and multi-node/ subdirectories." >&2
    exit 66
  }
done

say()  { printf '%s\n' "$*"; }
note() { printf '  %-8s %s\n' "$1" "$2"; }

# install <src> <dst> [mode]
# Copies only if different. In --check mode, reports and changes nothing.
install_file() {
  local src="$1" dst="$2" mode="${3:-0644}"
  if [ ! -r "$src" ]; then note "MISSING" "$src"; missing=1; return; fi
  if [ -f "$dst" ] && cmp -s "$src" "$dst"; then
    note "ok" "$dst"
    return
  fi
  changed=1
  if [ "$CHECK" = 1 ]; then
    note "DIFFERS" "$dst"
    return
  fi
  mkdir -p "$(dirname "$dst")"
  cp -- "$src" "$dst"
  chmod "$mode" "$dst"
  note "updated" "$dst"
}

# install_generated <src> <dst>
# Substitutes @@REPO@@ for the checkout path, then installs like any other file.
install_generated() {
  local src="$1" dst="$2" tmp
  if [ ! -r "$src" ]; then note "MISSING" "$src"; missing=1; return; fi
  tmp="$(mktemp)"
  {
    echo "# GENERATED by bootstrap.sh from $src"
    echo "# The checkout path is baked in. Re-run bootstrap.sh if the checkout moves."
    sed "s#@@REPO@@#$REPO#g" "$src"
  } > "$tmp"
  install_file "$tmp" "$dst"
  rm -f "$tmp"
}

say "repo:  $REPO"
say "role:  $ROLE$([ "$CHECK" = 1 ] && echo '  (check only, no changes)')"
say "host:  $(hostname)"
say ""

if [ "$ROLE" = "login" ]; then
  say "systemd units"
  install_file "$REPO/proxy/litellm.service"          "$UNITS/litellm.service"
  install_file "$REPO/proxy/litellm-postgres.service" "$UNITS/litellm-postgres.service"

  say ""
  say "proxy configuration"
  install_file "$REPO/proxy/litellm.yaml" "$HOME/litellm/litellm.yaml"

  say ""
  say "secrets"
  if [ -f "$HOME/litellm.env" ]; then
    note "ok" "$HOME/litellm.env exists, left untouched"
  else
    note "ACTION" "$HOME/litellm.env is missing"
    note "" "cp $REPO/proxy/litellm.env.example ~/litellm.env, fill in from Bitwarden, chmod 600"
  fi
fi

if [ "$ROLE" = "compute" ]; then
  say "node guard"
  if [ -x "$REPO/node-free-check.sh" ]; then
    note "ok" "$REPO/node-free-check.sh"
  else
    note "MISSING" "$REPO/node-free-check.sh (absent, or not executable: chmod +x)"
    missing=1
  fi

  say ""
  say "systemd units"
  # Both units reference the checkout by absolute path, because systemd has no notion
  # of "relative to the repo". Generated rather than copied, so re-run bootstrap if
  # the checkout ever moves.
  install_generated "$REPO/single-node/vllm@.service"            "$UNITS/vllm@.service"
  install_generated "$REPO/multi-node/vllm-multinode@.service"   "$UNITS/vllm-multinode@.service"

  say ""
  say "model configs (single node)"
  say "  note: a conf being present is not permission to start it. See the node"
  say "  allocation table in README.md."
  shopt -s nullglob
  for c in "$REPO"/single-node/models/*.conf; do
    install_file "$c" "$HOME/vllm/$(basename "$c")"
  done
  shopt -u nullglob

  say ""
  say "multi-node configuration"
  note "ok" "read directly from $REPO/multi-node, nothing to install"
fi

say ""
if [ "$missing" = 1 ]; then
  say "FATAL: one or more expected files were missing (see MISSING above)."
  say "       The repository is incomplete or you are in the wrong directory."
  exit 66
fi

if [ "$CHECK" = 1 ]; then
  if [ "$changed" = 1 ]; then
    say "Drift found. Re-run without --check to apply."
    exit 1
  fi
  say "In sync with the repo."
  exit 0
fi

if [ "$changed" = 1 ]; then
  say "Reloading systemd."
  if ! systemctl --user daemon-reload; then
    say ""
    say "WARNING: daemon-reload failed. The files are installed, but systemd has not"
    say "         picked them up. Run 'systemctl --user daemon-reload' by hand."
  fi
  say ""
  say "Done. Restart any affected service to pick up the change:"
  say "  systemctl --user restart <unit>"
  say "Remember that a multi-node deployment must be restarted on EVERY node."
else
  say "Nothing to do; already in sync."
fi
